// src/StatInput.tsx
export default function StatInput({
	value,
	onTextChange,
}: {
	value: string
	onTextChange: (text: string) => void
}) {
	return (
		<input
			className="w-full px-3 py-2 text-center transition-colors duration-200 border-2 border-gray-300 rounded-md shadow-inner focus:outline-none focus:border-orange-500"
			value={value}
			onInput={(event) => {
				onTextChange?.(event.currentTarget.value)
			}}
			onFocus={(event) => {
				event.currentTarget.select()
			}}
		/>
	)
}

// src/components/StatInput.vue
<!-- TODO: add min/max -->
<template>
	<input
		class="w-full px-3 py-2 text-center transition-colors duration-200 border-2 border-gray-300 rounded-md shadow-inner focus:outline-none focus:border-orange-500"
		v-bind="$attrs"
		:value="modelValue"
		@input="handleInput"
		@focus="$event.target.select()"
	/>
</template>

<script>
export default {
	props: {
		label: String,
		modelValue: Number,
	},

	setup(props, context) {
		return {
			handleInput(event) {
				context.emit("update:modelValue", Number(event.target.value) || 0)
			},
		}
	},
}
</script>
