// src/components/App.vue
<template>
	<main class="px-4 py-20">
		<form class="flex flex-col w-full max-w-md mx-auto space-y-4">
			<div class="flex flex-col p-4 space-y-4 bg-white rounded-md shadow-md">
				<h1 class="text-lg">Attacker</h1>
				<div class="grid grid-flow-col gap-4">
					<Field label="HP">
						<StatInput v-model="attacker.hp" />
					</Field>
					<Field label="ATK">
						<StatInput v-model="attacker.atk" />
					</Field>
					<Field label="DEF">
						<StatInput v-model="attacker.def" />
					</Field>
					<Field label="EVD">
						<StatInput v-model="attacker.evd" />
					</Field>
				</div>

				<OptionGroup
					class="self-start"
					name="attackerReaction"
					:options="[
						{ value: 'defend', text: 'Defend' },
						{ value: 'evade', text: 'Evade' },
					]"
					v-model="attackerReaction"
				/>
			</div>

			<button
				type="button"
				class="flex flex-col self-center p-2 space-y-4 text-white transition-colors duration-200 bg-orange-600 rounded-md shadow-md hover:bg-orange-500"
				title="Switch"
				@click="switchFighters"
			>
				<svg
					xmlns="http://www.w3.org/2000/svg"
					fill="none"
					viewBox="0 0 24 24"
					stroke="currentColor"
					class="w-8 h-8"
				>
					<path
						stroke-linecap="round"
						stroke-linejoin="round"
						stroke-width="2"
						d="M7 16V4m0 0L3 8m4-4l4 4m6 0v12m0 0l4-4m-4 4l-4-4"
					/>
				</svg>
			</button>

			<div class="flex flex-col p-4 space-y-4 bg-white rounded-md shadow-md">
				<h1 class="text-lg">Defender</h1>
				<div class="grid grid-flow-col gap-4">
					<Field label="HP">
						<StatInput v-model="defender.hp" />
					</Field>
					<Field label="ATK">
						<StatInput v-model="defender.atk" />
					</Field>
					<Field label="DEF">
						<StatInput v-model="defender.def" />
					</Field>
					<Field label="EVD">
						<StatInput v-model="defender.evd" />
					</Field>
				</div>

				<OptionGroup
					class="self-start"
					name="defenderReaction"
					:options="[
						{ value: 'defend', text: 'Defend' },
						{ value: 'evade', text: 'Evade' },
					]"
					v-model="defenderReaction"
				/>
			</div>

			<div class="p-4 space-y-1 bg-white rounded-md shadow-md" v-if="result">
				<p>
					Attacker wins <b>{{ percent(result.attackerWinRate) }}</b> of the
					time.
				</p>
				<p>
					Defender wins <b>{{ percent(result.defenderWinRate) }}</b> of the
					time.
				</p>
				<p>
					Both survive <b>{{ percent(result.nobodyWinRate) }}</b> of the time.
				</p>
			</div>
		</form>
	</main>
</template>

<script lang="ts">
import OptionGroup from "./OptionGroup.vue"
import StatInput from "./StatInput.vue"
import Field from "./Field.vue"
import { ref, watch, reactive, computed, watchEffect } from "vue"
import {
	createStatGroup,
	getDefenseRoundResult,
	getEvadeRoundResult,
} from "../battle"
import { count } from "../helpers"

type Reaction = "defend" | "evade"

export default {
	components: {
		OptionGroup,
		StatInput,
		Field,
	},
	setup() {
		const attacker = ref(createStatGroup())
		const attackerReaction = ref<Reaction>("defend")

		const defender = ref(createStatGroup())
		const defenderReaction = ref<Reaction>("defend")

		const result = ref<{
			attackerWinRate: number
			defenderWinRate: number
			nobodyWinRate: number
		}>()

		watchEffect(function simulate() {
			let wins = []

			for (let i = 0; i < 10000; i++) {
				const round1 =
					defenderReaction.value === "defend"
						? getDefenseRoundResult(attacker.value, defender.value)
						: getEvadeRoundResult(attacker.value, defender.value)

				if (round1.defenderHealth <= 0) {
					wins.push("attacker")
					continue
				}

				const round2 =
					attackerReaction.value === "defend"
						? getDefenseRoundResult(defender.value, attacker.value)
						: getEvadeRoundResult(defender.value, attacker.value)

				wins.push(round2.defenderHealth <= 0 ? "defender" : "nobody")
			}

			result.value = {
				attackerWinRate: count(wins, "attacker") / wins.length,
				defenderWinRate: count(wins, "defender") / wins.length,
				nobodyWinRate: count(wins, "nobody") / wins.length,
			}
		})

		function switchFighters() {
			;[
				attacker.value,
				defender.value,
				attackerReaction.value,
				defenderReaction.value,
			] = [
				defender.value,
				attacker.value,
				defenderReaction.value,
				attackerReaction.value,
			]
		}

		function percent(value: number) {
			return `${Math.round(value * 100)}%`
		}

		return {
			attacker,
			attackerReaction,
			defender,
			defenderReaction,
			result,
			percent,
			switchFighters,
		}
	},
}
</script>

// src/App.tsx
import { StateUpdater, useCallback, useState } from "preact/hooks"
import { Fighter, getDefenseRoundResult, getEvadeRoundResult } from "./battle"
import { count, mapValues, omit } from "./common"
import Field from "./Field"
import OptionGroup from "./OptionGroup"
import StatInput from "./StatInput"

type Reaction = "defend" | "evade"

const initialValues = {
	hp: "5",
	atk: "0",
	def: "0",
	evd: "0",
	reaction: "defend" as Reaction,
}

const toFighter = (values: typeof initialValues): Fighter =>
	mapValues(omit(values, ["reaction"]), (value) => Number(value) || 0)

export default function App() {
	const [attacker, setAttacker] = useState(initialValues)
	const updateAttacker = usePartialSetState(setAttacker)

	const [defender, setDefender] = useState(initialValues)
	const updateDefender = usePartialSetState(setDefender)

	const result = getBattleResult(
		toFighter(attacker),
		toFighter(defender),
		attacker.reaction,
		defender.reaction,
	)

	function swap() {
		setAttacker(defender)
		setDefender(attacker)
	}

	return (
		<main className="px-4 py-20">
			<form className="flex flex-col w-full max-w-md mx-auto space-y-4">
				<div className="flex flex-col p-4 space-y-4 bg-white rounded-md shadow-md">
					<h1 className="text-lg">Attacker</h1>

					<section className="grid grid-flow-col gap-4">
						<Field label="HP">
							<StatInput
								value={attacker.hp}
								onTextChange={(hp) => updateAttacker({ hp })}
							/>
						</Field>
						<Field label="ATK">
							<StatInput
								value={attacker.atk}
								onTextChange={(atk) => updateAttacker({ atk })}
							/>
						</Field>
						<Field label="DEF">
							<StatInput
								value={attacker.def}
								onTextChange={(def) => updateAttacker({ def })}
							/>
						</Field>
						<Field label="EVD">
							<StatInput
								value={attacker.evd}
								onTextChange={(evd) => updateAttacker({ evd })}
							/>
						</Field>
					</section>

					<section className="self-start">
						<OptionGroup<Reaction>
							name="attackerReaction"
							value={attacker.reaction}
							onChange={(reaction) => updateAttacker({ reaction })}
							options={[
								{ value: "defend", text: "Defend" },
								{ value: "evade", text: "Evade" },
							]}
						/>
					</section>

					<section>
						<p>
							<strong>{percent(result.nobodyWinRate)}</strong> chance of
							survival
						</p>
						<p>
							<strong>{percent(result.attackerWinRate)}</strong> chance of
							winning
						</p>
					</section>
				</div>

				<button
					type="button"
					className="flex flex-col self-center p-2 space-y-4 text-white transition-colors duration-200 bg-orange-600 rounded-md shadow-md hover:bg-orange-500"
					title="Swap"
					onClick={swap}
				>
					<svg
						xmlns="http://www.w3.org/2000/svg"
						viewBox="0 0 20 20"
						fill="currentColor"
						className="w-8"
					>
						<path d="M5 12a1 1 0 102 0V6.414l1.293 1.293a1 1 0 001.414-1.414l-3-3a1 1 0 00-1.414 0l-3 3a1 1 0 001.414 1.414L5 6.414V12zM15 8a1 1 0 10-2 0v5.586l-1.293-1.293a1 1 0 00-1.414 1.414l3 3a1 1 0 001.414 0l3-3a1 1 0 00-1.414-1.414L15 13.586V8z" />
					</svg>
				</button>

				<div className="flex flex-col p-4 space-y-4 bg-white rounded-md shadow-md">
					<h1 className="text-lg">Defender</h1>

					<section className="grid grid-flow-col gap-4">
						<Field label="HP">
							<StatInput
								value={defender.hp}
								onTextChange={(hp) => updateDefender({ hp })}
							/>
						</Field>
						<Field label="ATK">
							<StatInput
								value={defender.atk}
								onTextChange={(atk) => updateDefender({ atk })}
							/>
						</Field>
						<Field label="DEF">
							<StatInput
								value={defender.def}
								onTextChange={(def) => updateDefender({ def })}
							/>
						</Field>
						<Field label="EVD">
							<StatInput
								value={defender.evd}
								onTextChange={(evd) => updateDefender({ evd })}
							/>
						</Field>
					</section>

					<section className="self-start">
						<OptionGroup<Reaction>
							name="defenderReaction"
							value={defender.reaction}
							onChange={(reaction) => updateDefender({ reaction })}
							options={[
								{ value: "defend", text: "Defend" },
								{ value: "evade", text: "Evade" },
							]}
						/>
					</section>

					<section>
						<p>
							<strong>{percent(result.nobodyWinRate)}</strong> chance of
							survival
						</p>
						<p>
							<strong>{percent(result.defenderWinRate)}</strong> chance of
							winning
						</p>
					</section>
				</div>
			</form>
		</main>
	)
}

function usePartialSetState<T>(setState: StateUpdater<T>) {
	return useCallback(
		(partialUpdate: Partial<T>) => {
			setState((prev) => ({ ...prev, ...partialUpdate }))
		},
		[setState],
	)
}

function getBattleResult(
	attacker: Fighter,
	defender: Fighter,
	attackerReaction: Reaction,
	defenderReaction: Reaction,
) {
	let wins: Array<"attacker" | "defender" | "nobody"> = []

	for (let i = 0; i < 100000; i++) {
		const round1 =
			defenderReaction === "defend"
				? getDefenseRoundResult(attacker, defender)
				: getEvadeRoundResult(attacker, defender)

		if (round1.defenderHealth <= 0) {
			wins.push("attacker")
			continue
		}

		const round2 =
			attackerReaction === "defend"
				? getDefenseRoundResult(defender, attacker)
				: getEvadeRoundResult(defender, attacker)

		wins.push(round2.defenderHealth <= 0 ? "defender" : "nobody")
	}

	return {
		attackerWinRate: count(wins, "attacker") / wins.length,
		defenderWinRate: count(wins, "defender") / wins.length,
		nobodyWinRate: count(wins, "nobody") / wins.length,
	}
}

function percent(value: number) {
	return `${Math.round(value * 100)}%`
}
