// src/components/OptionGroup.vue
<template>
	<div
		class="flex flex-row overflow-hidden transition-colors duration-200 border-2 rounded-md focus-within:border-orange-500"
	>
		<label
			v-for="(option, index) of options"
			:key="index"
			:class="getLabelClass(option)"
		>
			<input
				type="radio"
				class="absolute opacity-0"
				:name="name"
				:value="option.value"
				@input="$emit('update:modelValue', $event.target.value)"
			/>
			<span class="select-none">{{ option.text }}</span>
		</label>
	</div>
</template>

<script lang="ts">
import { PropType } from "vue"
type Option = { text: string; value: string }

export default {
	props: {
		name: String,
		options: {
			type: Array as PropType<Option[]>,
			required: true,
		},
		modelValue: String,
	},

	setup(props) {
		return {
			getLabelClass(option: Option) {
				return [
					"px-3 py-2 transition-colors duration-200 cursor-pointer",
					props.modelValue === option.value
						? "bg-orange-600 text-white"
						: "hover:bg-orange-200",
				]
			},
		}
	},
}
</script>

// src/option-group.tsx
import type { Signal } from "@preact/signals"
import { Fragment } from "preact/jsx-runtime"

export function OptionGroup<T extends string>({
	name,
	options,
	valueSignal,
}: {
	name: string
	options: { label: string; value: T }[]
	valueSignal: Signal<T>
}) {
	return (
		<div class="flex border-2 rounded-md w-fit border-stone-300 dark:border-stone-500 overflow-clip focus-within:border-orange-500 dark:focus-within:border-orange-500">
			{options.map(({ label, value }) => (
				<Fragment key={value}>
					<label>
						<input
							type="radio"
							id="attackerReaction"
							name={name}
							class="peer sr-only"
							value={value}
							checked={valueSignal.value === value}
							onChange={() => {
								valueSignal.value = value
							}}
						/>
						<div class="peer-checked:bg-orange-600 peer-checked:text-white leading-none p-3 hover:bg-orange-400/30 transition cursor-pointer dark:bg-black/20  dark:hover:bg-orange-400/20 dark:peer-checked:hover:bg-orange-600">
							{label}
						</div>
					</label>
				</Fragment>
			))}
		</div>
	)
}
